In [2]:
import numpy as np

In [15]:
a = np.arange(1,10,1).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

从0开始索引，选取第二行第三列的元素

In [18]:
a[1,2]

6

选取第二行元素

In [19]:
a[1,:]

array([4, 5, 6])

选取第三列元素

In [23]:
a[:,2]

array([3, 6, 9])

选取从第一行开始到最后一行的所有行元素

In [20]:
a[1:,...]

array([[4, 5, 6],
       [7, 8, 9]])

In [21]:
a[...,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])